name: py311-pavement
channels:
  - conda-forge
dependencies:
  - python=3.11.9
  - pip>=24.0
  - pip:
    # dbt
    - dbt-duckdb>=1.0.0
    # map
    - geopandas>=0.14.4
    - folium>=0.17.0
    # dev
    - ruff>=0.0.271
    - yapf>=0.33.0
    - isort>=5.12.0
    - pytest>=7.3.1
    - ipython
    - jedi-language-server
