
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'pavement'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'pavement'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  pavement:
    # Config indicated by + and applies to all files under models/annot
    annot:
      +materialized: view

seeds:
  pavement:
    l0_annot_gt_cnt:
      +schema: annot
      +delimiter: ","
      +quote_columns: false
    l0_annot_pred_labeled_cls_category:
      +schema: annot
      +delimiter: "\t"
      +quote_columns: false
      +column_types:
        image: varchar(255)
        class: varchar(32)
        score_top1: float
        score_top2: float
        label_top1: int
        label_top2: int
    l0_annot_pred_labeled_cls_severity:
      +schema: annot
      +delimiter: "\t"
      +quote_columns: false
      +column_types:
        image: varchar(255)
        class: varchar(32)
        score_top1: float
        score_top2: float
        label_top1: int
        label_top2: int
    l0_annot_pred_unlabeled_cls_category:
      +schema: annot
      +delimiter: "\t"
      +quote_columns: false
      +column_types:
        image: varchar(255)
        class: varchar(32)
        score_top1: float
        score_top2: float
        label_top1: int
        label_top2: int
    l0_annot_pred_unlabeled_cls_severity:
      +schema: annot
      +delimiter: "\t"
      +quote_columns: false
      +column_types:
        image: varchar(255)
        class: varchar(32)
        score_top1: float
        score_top2: float
        label_top1: int
        label_top2: int
    l0_2023_exif:
      +delimiter: "\t"
      +quote_columns: false
      +column_types:
        prefix: varchar(255)
        image: varchar(64)
        height: int
        width: int
        altitude: float8
        timestamp: text
        latitude: float8
        longitude: float8
        easting: float8
        northing: float8
    l0_2023_map_image_feature:
      +delimiter: ","
      +quote_columns: false
      +column_types:
        prefix: varchar(255)
        image: varchar(64)
        feature_id: text
        distance: float8
    l0_2023_feat:
      +delimiter: "\t"
      +quote_columns: false
